### PR TITLE
needs install create-react-native-app

### PR DESCRIPTION
**Pull request by emtudo**

### CODE REVIEW

**Comment by chovy** [comment]
this should in package.json

**Comment by emtudo** [comment]
You're right, I did this: https://github.com/GeekyAnts/vue-native-core/pull/5

**Comment by emtudo** [comment]
reaopen because: https://github.com/GeekyAnts/vue-native-core/pull/5#discussion_r195105299

**Comment by neeraj-singh47** [comment]
@emtudo Can you close this PR as well. Thank you for your effort.

**Comment by emtudo** [comment]
Did I do wrong or did you not accept PRs?

**Comment by neeraj-singh47** [comment]
@emtudo We do accept PR's. The issue was that your PR was missing react-native-cli installation instructions and we cannot add preinstall scripts since it would keep installing for a package even if it exists.

**Comment by emtudo** [comment]
But this PR here specifically is to add in the README and not in the "preinstall" the other I already closed, this I opened even before that.

**Comment by neeraj-singh47** [comment]
@emtudo But you had not included the steps for react-native-cli

**Pull request closed without merging**
