### PR TITLE
v0.3.0

### LINKED ISSUE #17: Enable Travis CI / CircleCI

### LINKED ISSUE #216: trying to use vue-i18n
Tried to use vue-i18n with vue-native-core, and when attempting use with 

``` 
Vue.use(VueI18n);
```
I get this warning: [vue-i18n] vue-i18n (undefined) need to use Vue 2.0 or later (Vue: 0.1.4). Then when using $t() I get this error: [Vue warn]: Property or method "$t" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

### LINKED ISSUE #239: Warning: DatePickerAndroid has been merged with DatePickerIOS and will be removed in a future release.
**Description of the bug**
Warning about deprecated react native component using is printed on console when launching new repo following the installation tutorial. It is very annoying as it is on the same pipe than real errors.

**To Reproduce**
1. vue-native init my_project
2. npm install
3. npm run ios

**What I expected**
These warning should be fixed. Should we update the metro config or directly the vue-native-core module ?

**Screenshots**
image

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes

**Development platform (please complete the following information):**
 - OS: MAC
 - Shell/terminal: ZSH
-  Expo-cli: 3.13.6

**The device on which I run my Vue Native app**
 - Device: iPhone8
 - OS: last

### LINKED ISSUE #259: Stack traces display incorrect line numbers
**Description of the bug**
If an error is thrown in a Vue SFC, the line number of the statement that threw the error is incorrect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create SFC in .vue file
2. Throw an error in the `<script>` part of the SFC and don't handle it
3. View the stack trace in the error screen on the device/simulator or in the debugging tools

**What I expected**
The line number should match the line number in the user's source code

**Code sample**
```
<script>
export default {
  data() {
    return {
      message: 'Hello',
    };
  },
  methods: {
    p() {
      this.message += '!';
    },
  },
  mounted() {
    function t() {
      throw new Error('Mock error'); // line 15
    }
    t(); // line 17
    console.log(10 < 20);
  },
};
</script>

<template>
  <view class="container">
    <text class="text-color-primary">My Vue Native App</text>
    <text class="text-color-primary">{{ message }}</text>
    <button title="Press" @press="p" />
  </view>
</template>

<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.text-color-primary {
  color: blue;
}
</style>
```

**Screenshots**

**Did I use `vue-native-cli` to create the project?**
Yes

**Am I using Expo?**
Yes, although it also occurs on bare RN based projects

**Development platform:**
- OSX Catalina 10.15.4
- ZSH

**The device on which I run my Vue Native app**
 - Device: any iPhone or Android device
 - OS: all supported variants

### PR DESCRIPTION
**Pull request by RishabhKarnad**
PR for v0.3.0 release

- Fix issues with line number mapping in stack traces (fixes #259) - credit @rahul-mahato
- Adds Travis CI integration (resolves #17)
- Adds Jest config
- Fixes Flow config
- Removes unused dependencies
- Lint and format config
- Prevent auto-import of deprecated components (fixes #239)
- Set Vue version to 2.2.6 (fixes #216)

### CODE REVIEW

**Comment by RishabhKarnad** [comment]
Awaiting https://github.com/GeekyAnts/vue-native-core/issues/259

**Comment by RishabhKarnad** [comment]
Renamed to 0.3.0, since we need to make a release with some breaking changes, which we will call 0.2.0

**Comment by HakobiDev** [comment]
All developers will be glad if the 0.3.0 is supporting Vue 3 which is now in beta and ready to use.

**Comment by RishabhKarnad** [comment]
Just a note - Travis integration is extremely basic right now. It only builds and runs the single Jest test we have now.

We'll look into adding better automated tests in future releases.

**Comment by RishabhKarnad** [comment]
Will be releasing an RC release once #296 is merged.

**Pull request merged**
